name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
jobs:
  tests:
    defaults:
      run:
        working-directory: ./src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt -y update
          sudo apt -y upgrade
      - name: Run tests
        run: ./gradlew test
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
